/*
 * This C++ source file was generated by the Gradle 'init' task.
 */

#include <iostream>
#include <stdlib.h>
#include "native_plugin.h"

std::string native_plugin::Greeter::greeting() {
    return std::string("Hello, World!");
}
