/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package SEC2;

import java.util.*;
import java.nio.file.*;
import java.io.IOException;
import org.python.core.*;
import org.python.util.*;
import java.io.*;


public class App {

    private static final Scanner sc = new Scanner(System.in);
    public static void main(String[] args) 
    {
        double minX, maxX, incX;
        String expression;

        expression = getExpression();
        if (!expression.isEmpty())
        {
            minX = getXValues("Enter a minimum x value");
            maxX = getXValues("Enter a maximum x value");
            incX = getXValues("Enter an increment value");

            pyEvaluate(expression, minX, maxX, incX);
        }
        
    }

    /**
     * Get expression from users
     */
    public static String getExpression()
    {
        String input;
        
        System.out.println("SEC Assignment 2");
        System.out.println("Enter a math expression (unknown variables are denoted as x");
        System.out.println("Expression:> ");
        
        input = sc.nextLine();

        return input;
    }

    /**
     * get Real number user input
     */
    public static double getXValues(String prompt)
    {
        System.out.println(prompt);

        double input = sc.nextDouble();

        return input;
    }

    public static void pyEvaluate(String exp, double min, double max, double inc)
    {
        PythonInterpreter py = new PythonInterpreter();

        for(double x = min; x <= max; x += inc)
        {
            String subExp = exp.replaceAll("x", String.valueOf(x));
            double result = ((PyFloat) py.eval("float(" + subExp + ")")).getValue();
            System.out.println("Result: " + result);
        }
    }
}
